/**
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author LaDivina
 * 
 */
public class EvenFibonnaciNumbers {

	public static void main(String args[]) {
		long maxNumber = 4000000;
		long sum = 2;

		long number1 = 1;
		long number2 = 2;
		long newNumber = 0;

		while (newNumber <= maxNumber) {
			newNumber = number1 + number2;
			number1 = number2;
			number2 = newNumber;
			if(newNumber <= maxNumber && checkEvenNumber(newNumber)){
				sum += newNumber;
				System.out.println(newNumber);
			}
		}
		System.out.println("soma: " + sum);
	}

	private static boolean checkEvenNumber(long newNumber) {
		if(newNumber % 2 == 0){
			return true;
		}
		return false;
	}
}
